image: node:16.5.0
pages:
  stage: deploy
  tags:
    - stg-runner-tag
  cache:
    paths:
      - node_modules/
  script:
    - yarn install --registry https://nexus.huianrong.com/repository/npm-group/ # npm install
    - yarn docs:build # npm run docs:build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
