image: node:16.5.0
before_script:
  - npm i pnpm -g
  - pnpm install --registry=https://nexus.huianrong.com/repository/npm-group/
pages:
  stage: docs
  cache:
    paths:
      - node_modules/
  script:
    - pnpm run docs:build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
