image: node:16
pages:
  stage: deploy
  tags:
    - stg-runner-tag
  script:
    - pnpm install --registry https://nexus.huianrong.com/repository/npm-group/
    - pnpm run docs:build # npm run docs:build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
