// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText']
    IconCode: typeof import('@arco-design/web-vue/es/icon')['IconCode']
    IconCopy: typeof import('@arco-design/web-vue/es/icon')['IconCopy']
  }
}

export {}
